class: de.unihamburg.sickstore.database.SickStoreServer
port: 54000
queryHandler:
    class: de.unihamburg.sickstore.backend.QueryHandler
    warmup: 0
    logstaleness: true
    loglatency: true
    anomalyGenerator:
        class: de.unihamburg.sickstore.backend.anomaly.BasicAnomalyGenerator
        combinedGenerator:
            class: de.unihamburg.sickstore.backend.anomaly.MongoDbAnomalies
            defaultDelay: 0
            journalCommitInterval: 0
            customDelays:
                # to, from, delay
                - [primary, secondary1, 2]
                - [primary, secondary2, 4]
                - [secondary1, primary, 2]
                - [secondary2, primary, 4]
            tagSets:
                foobar:
                    A: 1
                    B: 2
    nodes:
        -
            class: de.unihamburg.sickstore.database.Node
            name: primary
            primary: true
            clientLatency: 2
            throughput:
                max: 10000.0
                hickupAfter: 0
                hickupDuration: 0
            tags:
                - A
                - B
        -
            class: de.unihamburg.sickstore.database.Node
            name: secondary1
            clientLatency: 2
            throughput:
                max: 10000.0
                hickupAfter: 0
                hickupDuration: 0
            tags:
                - A
        -
            class: de.unihamburg.sickstore.database.Node
            name: secondary2
            clientLatency: 2
            throughput:
                max: 10000.0
                hickupAfter: 0
                hickupDuration: 0
            tags:
                - B